version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    container_name: zig-tutorial-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_HOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - amqp-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  amqp-network:
    driver: bridge
    name: zig-amqp-network

volumes:
  rabbitmq_data:
    driver: local
    name: zig-tutorial-rabbitmq-data
